kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: demo-operator-frontend
subjects:
- kind: ServiceAccount
  name: demo-operator-frontend
roleRef:
  kind: Role
  name: demo-operator-frontend
  apiGroup: rbac.authorization.k8s.io
