apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mydemofrontends.demo.ibm.com
spec:
  group: demo.ibm.com
  names:
    kind: MyDemoFrontend
    listKind: MyDemoFrontendList
    plural: mydemofrontends
    singular: mydemofrontend
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            backend:
              description: Image is the Docker backend image to run for the daemon
              type: string
            image:
              description: Image is the Docker image to run for the daemon
              type: string
            label:
              description: Label is the value of the 'daemon=' label to set on a node
                that should run the daemon
              type: string
          required:
          - label
          - image
          - backend
          type: object
        status:
          type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
