apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-operator-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: demo-operator-backend
  template:
    metadata:
      labels:
        name: demo-operator-backend
    spec:
      serviceAccountName: demo-operator-backend
      containers:
        - name: demo-operator-backend
          # Replace this with the built image name
          image: niklaushirt/demo-operator-backend:v0.0.1
          command:
          - demo-operator-backend
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "demo-operator-backend"
